### ISSUE TITLE
The server side structure

### ISSUE THREAD

**Issue by Mangesh-P** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#11]
@moizKachwala The server side code works nicely but I feel there can be some more improvements in the structure.
It can be broken down by feature.
For eg If I want to create/remove a api for villain it is much more difficult.
Common code can be separated and Heroes code can be in it's own folder.

**Comment by moizKachwala** [comment]
can you please provide more details for the implementation ? also if you can raise the pull request then it would be great.

**Comment by esuarezz** [comment]
"Common code can be separated and Heroes code can be in it's own folder."

I think that problem usually comes from intellij, and it is when you are trying to move the code between folder, he refactorizes and it was not doing it in right way. I had that issue, check the pathto link the css,+html and logic if the paths are changing automatically..
RC7 was  up today xD! OMG every week a new release....

**Comment by moizKachwala** [comment]
at present no change in structure. Working on upgrading to RC7. Check the app hosted on heroku. Also added bootstrap support.

**Comment by esuarezz** [comment]
is it using now bootstrap css+js?

**Comment by moizKachwala** [comment]
not yet. only css. didn't find any good reason to add .js for demo application
