### ISSUE TITLE
Infinite restart after saving a file

### ISSUE THREAD

**Issue by zonkil** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#12]
After saving file and compile, nodemon go wild, restarting app all over again

![image](https://cloud.githubusercontent.com/assets/14218072/18526616/8afb2576-7ac1-11e6-88db-599eea2dab46.png)

**Comment by esuarezz** [comment]
Check the task you are executing just there is watching not watching + run

2016-09-14 20:26 GMT+01:00 zonkil notifications@github.com:

**Comment by zonkil** [comment]
I am executing:
`npm run deploy`
which execute
`"deploy": "concurrent --kill-others \"gulp watch\" \"gulp start\""`

**Comment by esuarezz** [comment]
if you want to deploy , I guess you dont need watch, just start ;) so remove watch from there.

Usually gulp makes problems if you try to watch + start, they disturb each other :P
let me know if u solve it :dancer: 

2016-09-14 20:37 GMT+01:00 zonkil notifications@github.com:

**Comment by zonkil** [comment]
If it should be removed why is it in package.json?

I haven't change anything, just downloded project and run as said in instruction.

**Comment by esuarezz** [comment]
you have to remove or start or watch, do that if you want to fix it. I
think you need to get the concept of open source, this is a project not
released to work in a company.. of course many things could be improved and
fixable

2016-09-14 21:06 GMT+01:00 zonkil notifications@github.com:

**Comment by esuarezz** [comment]
Check how it is build for example the task "default"

**Comment by zonkil** [comment]
I thought that it was make that way to automatic compile and restart. But it dosent work. If I start "default" or "start" it always is in infinite loop. If I only start "watch" I have to manualy restart.

And what concept of open source has to do with it? I found some issue and I am letting you know about it. You can just ignore it or do what ever you want.

**Comment by moizKachwala** [comment]
I have also faced the same issue and I am looking into this.

**Comment by zonkil** [comment]
I'm pretty new in all JS stuff, but removing `tasks: ['tslint']` from nodemon params helped (in some way, nodemon still restarting few times). `watch` execute `tslint` so `start` don't have to, I think.

**Comment by moizKachwala** [comment]
Yes, something wrong in watch and tslint. I notify when its fixed

**Comment by moizKachwala** [comment]
fixed
