### ISSUE TITLE
Error running: npm run build

### ISSUE THREAD

**Issue by santiim** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#13]
After running npm install, when running "npm run build" the following error occurs:
![image](https://cloud.githubusercontent.com/assets/12980852/18849454/748ddc42-8409-11e6-90fc-665978f23734.png)

I have on my computer:
Node 6.6.0
NPM 3.10.3

Thanks!

**Comment by moizKachwala** [comment]
Please make sure that you have gulp globally installed.

npm install gulp -g

Then delete node_modules folder from the project and do npm install again. This should resolve the issue.

**Comment by santiim** [comment]
Thanks for the reply;
**\- Install:** sudo npm install -g gulp
**\- Remove the directory**: node_modules
**\- I ran the command:** npm install
**\- finally run:** npm run build
The error is repeated;
![image](https://cloud.githubusercontent.com/assets/12980852/18879205/cb985fc6-84a9-11e6-8673-37c17cfc15d8.png)

**gulp version**
CLI version 3.9.1
Local version 3.9.1

**Comment by esuarezz** [comment]
Have you tried to run another different gulp configuration? did u check if
the postScript run after the npm install?

2016-09-27 16:06 GMT+01:00 Santiago Martini notifications@github.com:

**Comment by moizKachwala** [comment]
Hello,

It seems to be an machine specific issues. you can try couple of steps to resolve the issue.

 try running "npm rebuild node-sass"

And if this doesn't work then please take a fresh clone from git and try again.

**Comment by santiim** [comment]
Thanks  esuarezz, and Thanks again moizKachwala, After again from git clone, and run the "npm install" command, the following error occurs,
![image](https://cloud.githubusercontent.com/assets/12980852/18912102/12520a54-8557-11e6-94d2-90c3162c6f0d.png)

then run "sudo npm install typings -g", and "npm install" without errors, but run "npm run build" the following error:
![image](https://cloud.githubusercontent.com/assets/12980852/18915518/ad2e2372-8567-11e6-8f13-e03ec7dc86b0.png)

Could it be the version of node 6.6.0?

**Comment by santiim** [comment]
I solved the problem, generating the project in another directory. I could probably be due to permission issues, sorry for the inconvenience and my bad English, thank you very much!

**Comment by esuarezz** [comment]
cool santiago! and next time feel free to use spanish or italian with me :p
hehe
