### ISSUE TITLE
npm run deploy failed

### ISSUE THREAD

**Issue by jeehan24** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#15]
Hi, 
This is the first time that I'm creating a setup for an application on this scale and I am confused about some things. 
I tried downloading this to make it run but there seems to be an issue. It says "failed at the angular2-express-mongo@1.0.0 deploy script 'concurrent --kill-others "gulp watch" "gulp start". 
I updated both npm and node.js to the latest versions. 

I would really appreciate any help here. Thanks.

**Comment by moizKachwala** [comment]
can you please use the latest git clone and try installing the same. I think you are using the old name for the project.

Also add the screenshot for the error you are getting.

**Comment by jeehan24** [comment]
Hi,

Thanks for responding. I tried copying exactly how you did it on my own
folders. I'm attaching the errors I am getting after running npm install.

I am new at this and would really appreciate your help.

**Comment by jeehan24** [comment]
Hi again,

I worked on this a little more and this is what I have so far:

When I download and run your folder directly, it gives many semantic
"duplicate identifier" errors but it still builds and deploys without any
problems.
But when I create my own folder trying to use the exact same code as yours,
it gives further errors- I am attaching the screenshot of that. What is
happening is that when I run it using my own folders, the bin file does not
go to dist during building, which means there is a problem in building. The
terminal gave this error:

 "gulp-typescript: ts(tsProject) has been deprecated - use
.pipe(tsProject(reporter)) instead"

I don't understand why this issue doesn't exist when I use your setup as it
is.
Been trying to figure this out for a while. Any help will be greatly
appreciated.

**Comment by thomasmoldovan** [comment]
**"gulp-typescript: ts(tsProject) has been deprecated - use .pipe(tsProject(reporter)) instead"**
Do exactly what it sais: replace "ts(tsProject)" with "tsProject(reporter)" in gulpfile.ts

**"duplicate identifier"**
You have two variables with the same name, declared probably in 2 different places

My suggestion is to start a new project with this code base, and make sure it works. Then start adding components, modules, models one by one from your main project, making sure everything works after each step. This will give you a deeper understanding of the whole projects structure,  it will be easier to debug and will help you a lot in the long run.

**Comment by esuarezz** [comment]
it is for sure double declaration, because i remember i had to delete one
of then, just do it, i dont think , it shall to delete everything and
starting from scratch...

**Comment by moizKachwala** [comment]
it seems to be the machine/permission specific issue. Please try taking a new clone of repository
