### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by M00ker** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#16]
Hi

I followed you instructions to run the project and I get multiple "error TS2300: Duplicate identifier" errors when I run "npm run build".

Running "npm run deploy" gives me the following errors:
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! angular2-express-mongo@1.0.0 deploy: `concurrent --kill-others "gulp watch" "node ./dist/server/bin/www`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular2-express-mongo@1.0.0 deploy script 'concurrent --kill-others "gulp watch" "node ./dist/server/bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-express-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrent --kill-others "gulp watch" "node ./dist/server/bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-express-mongo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-express-mongo
npm ERR! There is likely additional logging output above.

Screenshots attached.

Thanks for your help.

![screen shot 2016-10-04 at 18 01 17](https://cloud.githubusercontent.com/assets/9038833/19084084/f7735070-8a5c-11e6-9d51-61f82e140d7a.png)
![screen shot 2016-10-04 at 18 00 36](https://cloud.githubusercontent.com/assets/9038833/19084089/fbdd19e8-8a5c-11e6-80a1-30addfcc9ed8.png)
![screen shot 2016-10-04 at 18 01 00](https://cloud.githubusercontent.com/assets/9038833/19084093/014265fa-8a5d-11e6-8525-1634bd21c52e.png)

**Comment by thomasmoldovan** [comment]
This is because of the new version of node 6.7.0, everything worked well in 6.6.0. I can see a lot of people having this issue recently.

**Comment by M00ker** [comment]
ok, thanks for the update.  I'll use Node 6.6.0 until there is a resolution.

All the best,
Peter

**Comment by hfournier** [comment]
@M00ker The error list above and your screenshot shows:
npm ERR! node **v4.6.0**
so it wouldn't have been due to node 6.7.0 as @thomasmoldovan suggested, although there could be other problems. But, the angular.io website says: "_Our examples require node **v5.x.x** or higher and npm 3.x.x or higher_"

**Comment by thomasmoldovan** [comment]
Every error line refers to @types/core-js, so it seems that is @types/core-js fault
run:
**"npm uninstall @types/core-js --save-dev"**
and everything will run ok (tested)

**Comment by moizKachwala** [comment]
thanks thomas for the fix.

**Comment by ikiraz18** [comment]
Hello, i am using Node 6.8.1 version and getting exception of @M00ker's write. This project works with only 6.6.0 version ? Can't update future time ? Thanks...
