### ISSUE TITLE
Ts files updated automatically generates no js files in the directory server

### ISSUE THREAD

**Issue by santiim** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#18]
When I create or modify a .ts in the **"client"** directory file automatically js in the **dist/client** directory files are updated, but when you edit or create a new ts file in the "server" directory, the files "js" in the **dist/server** directory they are not updated or generated automatically; only to run the **"npm run build"** command;
How I can solve this problem? thank you very much!

**Comment by esuarezz** [comment]
I will try to look it this week If I have time, I remember I included the
"watch" server folder

thank you for the report!

2016-10-06 15:24 GMT+01:00 Santiago Martini notifications@github.com:

**Comment by santiim** [comment]
Muchas gracias Elio por la rápida respuesta!! aguardo tu aviso, saludos!!

**Comment by moizKachwala** [comment]
issue is now fixed
