### ISSUE TITLE
Missing quote

### ISSUE THREAD

**Issue by florianbuehlmann** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#19]
Hi,

Thanks for sharing your project.

I found two minor issues:

In the package.json, a quote is missing:

At the line `concurrent --kill-others "gulp watch" "node ./dist/server/bin/www`

> sh: 1: Syntax error: Unterminated quoted string

that is because:

`"deploy": "concurrent --kill-others \"gulp watch\" \"node ./dist/server/bin/www",`
should be
`"deploy": "concurrent --kill-others \"gulp watch\" \"node ./dist/server/bin/www\"",`

After that change, the command works but throws:

> Warning: "concurrent" command is deprecated, use "concurrently" instead.

Changing the whole line to
`"deploy": "concurrently --kill-others \"gulp watch\" \"node ./dist/server/bin/www\"",`

looks like the best idea to me.

Also: Consider moving "Global Packages" above "Steps to Run", if both packages are really necessary in order to run it :-)

**Comment by moizKachwala** [comment]
thanks for the suggestions. changed in package.config. 

working on global packages. You can  also raise the pull request and become valuable contributor.
