### ISSUE TITLE
Property in Controller class can't used in the functions which are register in Routes

### ISSUE THREAD

**Issue by zzczzc004** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#22]
I want to add a property in the Controller class. Like in the HeroController, I add a 'test' property, and I want to use it in the create function. But when create is invoke by the route, it show **[TypeError: Cannot read property 'test' of undefined]**.

I think it's because typescript is simulate class but Javascript didn't have a class until ES6. I have use c# before and use Javascript and Typescript recently but not full understand it. 

```
class HeroController {

    test = "test";

    create(req: express.Request, res: express.Response): void {
        console.log(this.test);
    }
}
```

**Comment by zzczzc004** [comment]
I found I got an incorrect understanding about keywords this before, and solved the problem by change the way of register controller in the Routes.
Before:
`router.post("/heroes", controller.create);`
After:
`router.post("/heroes", (req, res) => controller.create(req, res));`

**Comment by zzczzc004** [comment]
I found 'this' in TypeScript is a common problem, here are some useful [blog](http://yehudakatz.com/2011/08/11/understanding-javascript-function-invocation-and-this/) and [wiki ](https://github.com/Microsoft/TypeScript/wiki/'this'-in-TypeScript) about understand it and how to avoid it.

**Comment by moizKachwala** [comment]
glad you got the resolution :)
