### ISSUE TITLE
Production version and upload to server

### ISSUE THREAD

**Issue by fedeVenturato** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#23]
Hi, thanks for making this excellent work available, I have a consultation; Always program in php and mysql; In this case, how do I put this application into operation on a server, and which hosting service should I use ?.

Thank you very much for helping this newbie!

**Comment by moizKachwala** [comment]
You will need a hosting provider (cloud) which has node preinstalled.

Couple of example where you can install is heroku, amazonaws etc.

you will find lot of examples for installing node js application.
