### ISSUE TITLE
No Typescript compilation error for Server

### ISSUE THREAD

**Issue by linvi** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#24]
Hello,

Thank you very much for this seed, I really like it.
I have an issue though with Typescript compilation.

TSLint is capable of identifying errors in the `Client` project.
But when creating an error in the `Server` project Typescript compiles fine and continues.

I will try to have a look into it but it would be great if you could.

Thanks and continue your good work.

Linvi

**Comment by linvi** [comment]
I finally changed 

``` js
gulp.watch(["server/src/**/*.ts"], ['compile']).on('change', function (e) {
        console.log('TypeScript file ' + e.path + ' has been changed. Compiling.');
    });
```

into

``` js
gulp.watch(["server/src/**/*.ts"], ['build:server']).on('change', function (e) {
        console.log('TypeScript file ' + e.path + ' has been changed. Compiling.');
    });
```

**Comment by moizKachwala** [comment]
great, you can raise the pull request
