### ISSUE TITLE
Heroku won't build

### ISSUE THREAD

**Issue by asherbitton** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#25]
Hi,

Took a clean clone and tried to build on heroku and got and error (root cause is postinstall getting sh: 1: gulp: not found), full log below:
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version (latest stable) via semver.io...
remote:        Downloading and installing node 6.9.1...
remote:        Using default npm version: 3.10.8
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:
remote:        > angular2-express-mongo@1.0.0 postinstall /tmp/build_56187b5af97a2c7f8c055e26751acb6a
remote:        > gulp installTypings
remote:
remote:        sh: 1: gulp: not found
remote:
remote:        npm ERR! Linux 3.13.0-100-generic
remote:        npm ERR! argv "/tmp/build_56187b5af97a2c7f8c055e26751acb6a/.heroku/node/bin/node" "/tmp/build_56187b5af97
a2c7f8c055e26751acb6a/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_56187b5af97a2c7f8c055e2
6751acb6a/.npmrc"
remote:        npm ERR! node v6.9.1
remote:        npm ERR! npm  v3.10.8
remote:        npm ERR! file sh
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno ENOENT
remote:        npm ERR! syscall spawn
remote:        npm ERR! angular2-express-mongo@1.0.0 postinstall: `gulp installTypings`
remote:        npm ERR! spawn ENOENT
remote:        npm ERR!
remote:        npm ERR! Failed at the angular2-express-mongo@1.0.0 postinstall script 'gulp installTypings'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the angular2-express-mongo package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     gulp installTypings
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs angular2-express-mongo
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls angular2-express-mongo
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_56187b5af97a2c7f8c055e26751acb6a/npm-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        - Gulp may not be tracked in package.json
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked
-dependencies
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to kukutest.
remote:
To https://git.heroku.com/kukutest.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/kukutest.git'

Any help will be appreciated.

**Comment by moizKachwala** [comment]
this error is because, heroku doesn't have gulp installed globally. 

You can either pull the gulp dependencies from dev to main dependencies as dev dependencies does not get installed in heroku

or else you can turn on the settings to install dev dependencies.

and once this is done, you can call the full path from node_modules/gulp .... (path for gulp executable) and then run the gulp command.

**Comment by asherbitton** [comment]
Thanks for the workaround, moved dev dependencies, build is now working.
