### ISSUE TITLE
how to use scss

### ISSUE THREAD

**Issue by linfengluo** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#27]
how can i use scss in project?

**Comment by raphael-brand** [comment]
take look here: https://www.npmjs.com/package/gulp-sass

**Comment by Valonix** [comment]
it will be cool if SCSS will be from the box too ;) 
Thanks for boilerplate...

**Comment by moizKachwala** [comment]
I am planning to move to scss and you will get it soon
