### ISSUE TITLE
can we replace type script code with regular javascript in server side?

### ISSUE THREAD

**Issue by injrav** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#29]
very very good example.
But I am not able to find the main reason of using typescript in server side
Can we replace type script code  with regular javascript in server module? if yes what changes we need to make?

**Comment by moizKachwala** [comment]
Typescript is the subset of javascript.  So in background this is going to be converted to javascript.

The only point of writing in Typescript to leverage some of the great advantages of typescript like typings, dataTypes, compile time errors etc.
