### ISSUE TITLE
Webpack or SystemJS

### ISSUE THREAD

**Issue by belyeu** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#30]
Hello, I'm new to angular 2, but would like to know how you feel about using webpack vs systemjs. Ive searched the web and found mixed results.
I love your approach, but wouldn't want to plunge into systemJS if everything is converting to webpack. Ive been trying for days now to convert your app to webpack without much success. Is it worth the effort?
 Great work!!

**Comment by moizKachwala** [comment]
Hello,

Yes that is already in my list. will add that  soon.

**Comment by danielpiedra** [comment]
@moizKachwala any updates on this subject? I would really love to use this with webpack as bundler.

**Comment by moizKachwala** [comment]
yes on my list. even you can update and raise the pull request. I will merge.

**Comment by danielpiedra** [comment]
ok, will give it  try later today!
