### ISSUE TITLE
How to use forever

### ISSUE THREAD

**Issue by Valonix** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#32]
I tried to use forever but my server doesn`t work.

root@app:/opt/dist/server/bin# sudo forever start www
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: www

But server response is ERR_CONNECTION_REFUSED

Also if i do some changes in html clients file, i had this error in browser console

shim.min.js:1 Uncaught SyntaxError: Unexpected token <
zone.js:1 Uncaught SyntaxError: Unexpected token <
Reflect.js:1 Uncaught SyntaxError: Unexpected token <
system.src.js:1 Uncaught SyntaxError: Unexpected token <
systemjs.config.js:1 Uncaught SyntaxError: Unexpected token <
5879663…:21 Uncaught ReferenceError: System is not defined
    at 5879663…:21
(anonymous) @ 5879663…:21

But i didn`t touch any .js files :(

**Comment by moizKachwala** [comment]
Please follow all the steps mentioned in the ReadMe
