### ISSUE TITLE
Decrease request during loading.

### ISSUE THREAD

**Issue by fedeVenturato** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#33]
Hi, you can see that it performs 80 requests during its load. Is it possible to reduce this number of requests? To increase the loading speed. Thank you!!

**Comment by fedeVenturato** [comment]
I change the question, could someone tell me how Configure Ahead of Time (AoT) compilation.

**Comment by moizKachwala** [comment]
I think you need to do a production build, where it will bundle and minify the  file.
