### ISSUE TITLE
ZoneAwareError on adding npm package

### ISSUE THREAD

**Issue by hiteshagja** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#37]
I have clone this repo and when I tried to use angular2-flash-messages I am getting 
```
ZoneAwareError {__zone_symbol__error: Error: Unexpected token <
  Evaluating http://localhost:3000/angular2-flash-messages
  Evaluating ...
```
This happens with all the packages. 

Let me know what am I doing wrong?

**Comment by moizKachwala** [comment]
fixed, updated packages and typings
