### ISSUE TITLE
Unable to add Angular Material

### ISSUE THREAD

**Issue by cliffeby** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#41]
Followed https://material.angular.io/guide/getting-started and get Loading...  Error reports are light
Console:
Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:3000/app/app.module.js:13:18)
	    at eval (http://localhost:3000/app/app.module.js:50:4)
	    at eval (http://localhost:3000/app/app.module.js:51:3)
	Evaluating http://localhost:3000/@angular/material
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:3000/app/app.module.js:13:18)
	    at eval (http://localhost:3000/app/app.module.js:50:4)
	    at eval (http://localhost:3000/app/app.module.js:51:3)
	Evaluating http://localhost:3000/@angular/material
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
(anonymous) @ (index):23
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:141
(anonymous) @ zone.js:818
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:191
drainMicroTaskQueue @ zone.js:584
ZoneTask.invoke @ zone.js:490

**Comment by moizKachwala** [comment]
did you register that in systemjs file ?

**Comment by cliffeby** [comment]
Yes.  I included `'@angular/material': 'npm:@angular/material/bundles/material.umd.js'` to the var map object in systemjsconfig.js

**Comment by moizKachwala** [comment]
also you need to add the entry in gulpfile.ts

**Comment by jankrib** [comment]
I have the same issue. Which entry should be added to gulpfile.ts?

**Comment by jankrib** [comment]
For me it worked adding this:

```
  var ngPackageNames = [
    ...
    'material',
    'cdk',
    'animations'
  ];
```

**Comment by moizKachwala** [comment]
great 👍
