### ISSUE TITLE
Asking for modification

### ISSUE THREAD

**Issue by esuarezz** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#6]
Hi! i wanted to write you a comment but i dont know how i can :S

https://github.com/moizKachwala/Angular2-expressjs-mongoose-gulp-node-typescript/blob/master/server/src/config/routes/HeroRoutes.ts

why dont you inject the controller? so u can delete that = new hero controller

**Comment by moizKachwala** [comment]
Presently updating the modules to latest RC5, so I will pick those changes in that.

**Comment by esuarezz** [comment]
(I am getting some npm warn when npm install about deprecated)
Thanks!! when do you think you will have that changes? if you are going to spend time to do it, I can do it for you ,

I wanted to tell you, you have done a very good job, the code is really cleaned , when I read it I thought I was in Java :P and always that is nice, sometimes is hard start to do a project from scratch when you are not expert in that language and you get frustrated with clean code , so I was trying to find something where I could see a nice example cleaned and I found this,

Good job :dancer:

**Comment by esuarezz** [comment]
npm WARN package.json angular2-express@1.0.0 No repository field.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN peerDependencies The peer dependency typescript@>=1.7.3 included from tslint will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency reflect-metadata@0.1.2 included from angular2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency rxjs@5.0.0-beta.6 included from angular2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency zone.js@^0.6.12 included from angular2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> angular2-express@1.0.0 postinstall C:\Users\Elio\Desktop\workspace\bot-property
> gulp installTypings

[12:11:31] Failed to load external module ts-node/register
[12:11:31] Failed to load external module typescript-node/register
[12:11:31] Failed to load external module typescript-register
[12:11:31] Failed to load external module typescript-require
                                                           [12:11:51] Using gulpfile ~\Desktop\workspace\bot-property\gulpfile.ts
[12:11:51] Starting 'installTypings'...
[12:11:53] Finished 'installTypings' after 1.93 s
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package reflect-metadata@0.1.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.17 wants reflect-metadata@0.1.2

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Elio\Desktop\workspace\bot-property\npm-debug.log

**Comment by moizKachwala** [comment]
Glad you liked it. I am working on this warnings. Please use latest node and also try and install gulp globally and directly fire the commands from console rather than running through npm.

this will get fixed soon. If you are fixing than it would be great. You can raise a pull request.

**Comment by esuarezz** [comment]
I installed gulp globally

[12:26:08] Failed to load external module ts-node/register
[12:26:08] Failed to load external module typescript-node/register
[12:26:08] Failed to load external module typescript-register
[12:26:08] Failed to load external module typescript-require
[12:26:32] Using gulpfile ~\Desktop\workspace\bot-property\gulpfile.ts
[12:26:32] Starting 'installTypings'...
[12:26:34] Finished 'installTypings' after 2.32 s
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package reflect-metadata@0.1.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.17 wants reflect-metadata@0.1.2

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Elio\Desktop\workspace\bot-property\npm-debug.log

**Comment by moizKachwala** [comment]
the error is ok.. I am fixing that. now you can run npm run build and then do npm run start

**Comment by esuarezz** [comment]
I could solve some of them but I cant do more ..

[12:35:12] Starting 'installTypings'...
[12:35:14] Finished 'installTypings' after 2.24 s
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package reflect-metadata@0.1.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.17 wants reflect-metadata@0.1.2

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Elio\Desktop\workspace\bot-property\npm-debug.log

**Comment by esuarezz** [comment]
After doing many things...

I got the same issue than one guy and I did npm build too..

https://github.com/moizKachwala/Angular2-expressjs-mongoose-gulp-node-typescript/issues/4

**Comment by moizKachwala** [comment]
please run command, gulp build and then do npm run start

**Comment by esuarezz** [comment]
now I could run it ! not experience with gulp before :P.  now i could run
it, I connected to my mongo but then is "loading", I check console on
chrome and I see: Rx.js:1 Uncaught SyntaxError: Unexpected token <
angular2-polyfills.js:349 Error: (SystemJS) Unexpected token
<(…)ZoneDelegate.invoke @ angular2-polyfills.js:349

2016-08-25 13:09 GMT+01:00 Moiz Kachwala <notifications@github.com>:

**Comment by esuarezz** [comment]
I did some fixes, I will create a pull request, now the dependencies are working fine, 
I am going to try to fix that errors we get at the beginning and everything fine.... After that working fine I will migrate to RC5 if you want..

I am going to use this as base from an application I want to develop, and this has helped me a lot :D

**Comment by moizKachwala** [comment]
that would be great. I really appreciate your contribution.

**Comment by esuarezz** [comment]
I am trying to update to Rc5 , but cant get it... I think the issue is
comingo from the route so I dont get any exception in the console, but them
I cant see any resault in the screen, just the tipical "loading"

Then I tried to do it simple, and always I dont get any error but of course is not working, so something is wrong there, because it doesnt work buy any exception is raised in console..

**Comment by moizKachwala** [comment]
there are some major changes for RC5 in router and other modules. Also I need to add the bundler for systemJS to integrate with gulp. Presently I am using the beta version of Angular so need heavy refactoring for the same.

Please be patient, I am working on the same and will get implemented within few days.

**Comment by esuarezz** [comment]
Ok Moiz, then I let you to finish it, I am watching, so I will receive the
changes

2016-08-25 18:07 GMT+01:00 Moiz Kachwala <notifications@github.com>:

**Comment by esuarezz** [comment]
are u thinking to automatize gulp or smth or show errors when something is
wrong?

2016-08-25 18:20 GMT+01:00 Elio Suarez Santana <esuarez.gcc@gmail.com>:

**Comment by esuarezz** [comment]
Well I will do tomorrow a pull request, i could fix the gulp file , and now we have just that 
[02:03:25] Failed to load external module ts-node/register
[02:03:25] Failed to load external module typescript-node/register
[02:03:25] Failed to load external module typescript-register
[02:03:25] Failed to load external module typescript-require

So, if you know more or lesss, you can tell me and I can fix it, after that I will try the migration to Rc5, I added logs and bla bla and now much better..
Now is watching correctly and the task are completely fine and using rc5 not beta anymore , but I dont know if I will have the same problem when I try to bootstrap the app , I will let you know tomorrow ;)

**Comment by moizKachwala** [comment]
things have been updated to RC5. I have also introduced systemjs.config.js to load modular dependencies.
Also I have commented the old code and readd the router modules as have changed drastically in RC release. It would be great if you can raise the pull request.

**Comment by esuarezz** [comment]
I get this in console:
Failed to parse SourceMap: http://localhost:3000/libs/core-js/client/shim.min.js.map
Failed to parse SourceMap: http://localhost:3000/libs/reflect-metadata/Reflect.js.map

And the same issues with : [02:03:25] Failed to load external module ts-node/register
[02:03:25] Failed to load external module typescript-node/register
[02:03:25] Failed to load external module typescript-register
[02:03:25] Failed to load external module typescript-require

and the routes are not working, so just i can see updated to rc5

**Comment by moizKachwala** [comment]
fixed everything. You can ignore those errors. The app will work fine.

**Comment by esuarezz** [comment]
Thank you for everything, you have done a very good job.
but why are that errors? perhaps I can fix them, or will u fix them?

**Comment by moizKachwala** [comment]
just install this globally and that should run away.

npm install ts-node -g
npm install typescript-node -g

**Comment by esuarezz** [comment]
should we include this in the readme or smth?

**Comment by moizKachwala** [comment]
done :)

**Comment by esuarezz** [comment]
I had to install this:

npm install typescript-register ts-node locally

I did it with a second download from here, and that worked to fix it, could we include it in the package.json or any part?

and i have another question, about this:
Failed to parse SourceMap: http://localhost:3000/libs/core-js/client/shim.min.js.map
Failed to parse SourceMap: http://localhost:3000/libs/reflect-metadata/Reflect.js.map

Do you know why is happening? perhaps i can try to fix it

**Comment by moizKachwala** [comment]
yes we can, but I don't see any harm without that in application.

The failed message you seeing in the browser is because system.js is not able to find the .map files as I have only copied .js files via gulp. I we include .map files then it will not give error. but again if we don't then it doesn't effect the application.

**Comment by esuarezz** [comment]
good job! i will add you on linkedin dude :)
