### ISSUE TITLE
Failed to load external modules

### ISSUE THREAD

**Issue by davidRsully** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#8]
Some errors when running:
[1] Failed to load external module ts-node/register
[1] [08:10:48] Failed to load external module typescript-node/register
[1] [08:10:48] Failed to load external module typescript-register
[1] [08:10:48] Failed to load external module typescript-require

**Comment by esuarezz** [comment]
check this package.json and add them, after that npm install:

  "devDependencies": {
    "@types/core-js": "^0.9.32",
    "concurrently": "^2.2.0",
    "morgan": "1.7.0",
    "del": "^2.2.0",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-nodemon": "^2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-tslint": "^4.3.3",
    "gulp-typescript": "^2.13.6",
    "gulp-typings": "^2.0.0",
    "method-override": "^2.3.6",
    "run-sequence": "^1.2.1",
    "tslint": "^3.5.0",
    "ts-node": "1.3.0",
    "typescript-register": "1.1.0",
    "typescript": "^1.8.10",
    "typings": "^1.3.2"
  },

**Comment by davidRsully** [comment]
This did the trick, thanks so much. I added 
"ts-node": "1.3.0",
And everything is running without those errors.

I also changed line 9 of the package.json file from:
"start": "concurrent --kill-others \"gulp watch\" \"gulp start\”",
To:
"start": "concurrently --kill-others \"gulp watch\" \"gulp start\"",

I was looking for a way to get the data returned sorted, and so on line 25 of the BaseRepositoriy.ts I added the following.

```
retrieve (callback: (error: any, result: any) => void) {
    this._model.find({}, callback).sort({name: 1})
}
```

This works well enough, but do you know of a way to make it a dynamic param?

David Sullivan
David.R.Sully@Gmail.com

**Comment by moizKachwala** [comment]
I will add the "ts-node": "1.3.0", in the dev dependency and close this issue.
