### ISSUE TITLE
the app dont run

### ISSUE THREAD

**Issue by tluanga** [moizKachwala/Angular2-Typescript-MongoDb-ExpressJs-NodeJs#9]
the app dont run, it just stuck on loading page please help

**Comment by moizKachwala** [comment]
what is the error  on npm ? did you started mongo db at a specific port

**Comment by Mangesh-P** [comment]
👍 On console it gives error.
localhost/:19 Error: SyntaxError: Unexpected token <(…).
No error on npm console.It is connected to mongodb

**Comment by tluanga** [comment]
![error](https://cloud.githubusercontent.com/assets/1406978/18424951/854dbd5a-78d2-11e6-8a0a-e33cf5658df0.png)
im getting this error

**Comment by moizKachwala** [comment]
fixed.
